#!/bin/bash
# lib/common.sh — engine detection, the compose() wrapper, ramalama
# resolution, and rendering of extra mounts. Sourced by ai-agent
#
# Picks Podman by default, falls back to Docker if podman isn't found,
# and layers compose.mounts.override.yaml on top (if present) so extra
# mounts from conf/pi-mounts.conf never override the base ones defined in
# compose.yaml.

ENGINE="podman"
COMPOSE_CMD="podman-compose"
COMPOSE_FILES=(-f "$DIR/compose.yaml")

command -v podman &> /dev/null || { ENGINE="docker"; COMPOSE_CMD="docker compose"; }
[ -f "$DIR/compose.mounts.override.yaml" ] && COMPOSE_FILES+=(-f "$DIR/compose.mounts.override.yaml")
compose() { $COMPOSE_CMD "${COMPOSE_FILES[@]}" "$@"; }

# Makes sure 'ramalama' is resolvable even when the calling process (e.g.
# VSCode spawning the pi wrapper) doesn't inherit the interactive shell's
# PATH: checks PATH, then RAMALAMA_BIN_DIR, then common install locations.
resolve_ramalama() {
    command -v ramalama >/dev/null 2>&1 && return 0

    local CANDIDATES=(
        "${RAMALAMA_BIN_DIR:-}"
        "$HOME/.local/bin"
        "$HOME/.local/pipx/venvs/ramalama/bin"
        "/usr/local/bin"
        "/usr/bin"
    )
    for dir in "${CANDIDATES[@]}"; do
        if [ -n "$dir" ] && [ -x "$dir/ramalama" ]; then
            export PATH="$dir:$PATH"
            return 0
        fi
    done

    echo "[Error] 'ramalama' not found in PATH or common install locations." >&2
    echo "        Set RAMALAMA_BIN_DIR in env.conf to its install directory." >&2
    return 1
}

# Renders conf/pi-mounts.conf into a compose override that appends those
# volumes to pi-agent. ensure_environment() calls this automatically on
# every --setup/--start, so it stays current without a manual step.
render_mounts() {
    local SRC="$DIR/conf/pi-mounts.conf"
    local OUT="$DIR/compose.mounts.override.yaml"
    [ -f "$SRC" ] || { echo "[Mounts] No pi-mounts.conf found, skipping."; return 0; }

    {
        echo "# Auto-generated by pi-ramalama --render-mounts from pi-mounts.conf. Do not edit."
        echo "services:"
        echo "  pi-agent:"
        echo "    volumes:"
        local n=0
        while IFS= read -r line; do
            line="${line%%#*}"
            line="$(echo "$line" | xargs)"
            [ -z "$line" ] && continue
            line="${line/#\~/$HOME}"
            echo "      - ${line}"
            n=$((n+1))
        done < "$SRC"
        [ "$n" -eq 0 ] && echo "      []"
    } > "$OUT"
    echo "[Mounts] Rendered $n extra mount(s) from pi-mounts.conf -> $OUT"
}

# Signals (does not install) missing host dependencies.
# Runs on every pi-ramalama invocation.
check_dependencies() {
    local MISSING=0

    if ! command -v podman &>/dev/null && ! command -v docker &>/dev/null; then
        echo "[Missing] No OCI engine found (podman or docker)." >&2
        echo "           Install one, e.g.: sudo apt install podman" >&2
        MISSING=1
    fi

    if ! resolve_ramalama 2>/dev/null; then
        echo "[Missing] 'ramalama' CLI not found." >&2
        echo "           Install it: pipx install ramalama  (or: pip3 install --user ramalama)" >&2
        echo "           Or run: $DIR/requirements.sh" >&2
        MISSING=1
    fi

    if ! command -v curl &>/dev/null; then
        echo "[Missing] 'curl' not found (required by ai-agent's healthchecks)." >&2
        MISSING=1
    fi

    [ "$MISSING" -eq 0 ]
}

# Drops a stale pi-agent container (exists but not running) before a fresh
# 'compose up', so a leftover from a previous crash doesn't block the start.
ensure_pi_agent_removed() {
    if $ENGINE ps -a --format '{{.Names}}' 2>/dev/null | grep -qx pi-agent \
       && ! $ENGINE ps --format '{{.Names}}' 2>/dev/null | grep -qx pi-agent; then
        $ENGINE rm -f pi-agent >/dev/null 2>&1 || true
    fi
}
